- name: openconfig-bfd
  docs:
    - yang/bfd/openconfig-bfd.yang
  build:
    - yang/bfd/openconfig-bfd.yang
  run-ci: true
- name: openconfig-bfd-ni
  build:
    - yang/bfd/openconfig-bfd.yang
    - yang/network-instance/openconfig-network-instance.yang
  run-ci: true
