substitutions:
    _OC_PYANG_VERSION: master

steps:
############### GET CI REPO ###############
# Decrypt the file containing the key
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=keyring0
  - --key=key0
  volumes:
  - name: 'ssh'
    path: /root/.ssh
# Set up git with key and domain
# See https://cloud.google.com/build/docs/access-github-from-build#add_the_public_ssh_key_to_known_hosts
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

############### COMMON PREP ###############
# Create GOPATH
- name: 'golang'
  entrypoint: 'bash'
  args: ['-c', 'mkdir -p /go/src/github.com/openconfig']
  volumes:
  - name: 'gopath'
    path: /go
  id: 'go path creation'
# Clone CI repository
- name: 'golang'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git clone git@github.com:openconfig/models-ci.git /go/src/github.com/openconfig/models-ci
    cd /go/src/github.com/openconfig/models-ci
    # Modify the major version to update models-ci version.
    #branch=$(git tag -l 'v10.*' | sort -V | tail -1)
    branch=pyangbind-version
    git checkout $branch
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'gopath'
    path: /go
  id: 'models-ci clone'
# Get CI script dependencies
- name: 'golang'
  entrypoint: 'go'
  args:
  - 'install'
  - './...'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'gopath'
    path: /go
  env:
  - 'GOPATH=/go'
  dir: '/go/src/github.com/openconfig/models-ci'
  id: 'models-ci dep'
# Generate validator scripts
- name: 'golang'
  entrypoint: 'bash'
  args:
  - -c
  - >- # CI Configuration
    /go/bin/cmd_gen
    -modelRoot=$_MODEL_ROOT
    -repo-slug=$_REPO_SLUG
    -pr-head-repo-url=$_HEAD_REPO_URL
    -commit-sha=$COMMIT_SHA
    -pr-number=$_PR_NUMBER
    -skipped-validators=confd,yanglint
    -extra-pyang-versions=2.2.1
    -branch=$BRANCH_NAME
    #-compat-report=pyangbind
  secretEnv: ['GITHUB_ACCESS_TOKEN']
  env:
  - 'GOPATH=/go'
  volumes:
  - name: 'gopath'
    path: /go
  id: 'validator prep'

############### REGEXP TESTS ###############
# Clone CI repository
- name: 'golang'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git clone git@github.com:openconfig/pattern-regex-tests.git /go/src/github.com/openconfig/pattern-regex-tests
    cd /go/src/github.com/openconfig/pattern-regex-tests
    # Modify the major version to update regexp version.
    branch=$(git tag -l 'v2.0*' | sort -V | tail -1)
    git checkout $branch
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'gopath'
    path: /go
  waitFor: ['validator prep']
  id: 'regexp clone'
# Get regexp dependencies
- name: 'golang'
  entrypoint: 'go'
  args: ['install', './...']
  volumes:
  - name: 'gopath'
    path: /go
  env:
  - 'GOPATH=/go'
  dir: '/go/src/github.com/openconfig/pattern-regex-tests'
  waitFor: ['regexp clone']
  id: 'regexp dep'
- name: 'us-west1-docker.pkg.dev/$PROJECT_ID/models-ci/models-ci-image'
  entrypoint: 'bash'
  args: ['-c', "/go/src/github.com/openconfig/models-ci/validators/regexp/test.sh"]
  secretEnv: ['GITHUB_ACCESS_TOKEN']
  env:
  - 'GOPATH=/go'
  - '_PR_NUMBER=$_PR_NUMBER'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - '_MODEL_ROOT=$_MODEL_ROOT'
  - '_REPO_SLUG=$_REPO_SLUG'
  - 'BRANCH_NAME=$BRANCH_NAME'
  volumes:
  - name: 'gopath'
    path: /go
  waitFor: ['regexp dep']
  id: 'regexp'

############### YANGLINT ##############
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://openconfig/libyang.deb', '/workspace/libyang.deb']
  waitFor: ['validator prep']
  id: 'yanglint prep1'
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://openconfig/yanglint.deb', '/workspace/yanglint.deb']
  waitFor: ['validator prep']
  id: 'yanglint prep2'
- name: 'us-west1-docker.pkg.dev/$PROJECT_ID/models-ci/models-ci-image'
  entrypoint: 'bash'
  args: ['-c', "/go/src/github.com/openconfig/models-ci/validators/yanglint/test.sh"]
  secretEnv: ['GITHUB_ACCESS_TOKEN']
  volumes:
  - name: 'gopath'
    path: /go
  env:
  - 'GOPATH=/go'
  - '_PR_NUMBER=$_PR_NUMBER'
  - '_MODEL_ROOT=$_MODEL_ROOT'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - '_REPO_SLUG=$_REPO_SLUG'
  - 'BRANCH_NAME=$BRANCH_NAME'
  waitFor: ['yanglint prep1', 'yanglint prep2']
  id: 'yanglint'

############### MISC-CHECKS ###############
- name: 'golang'
  entrypoint: 'bash'
  args: ['-c', "/go/src/github.com/openconfig/models-ci/validators/misc-checks/test.sh"]
  secretEnv: ['GITHUB_ACCESS_TOKEN']
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'gopath'
    path: /go
  env:
  - 'GOPATH=/go'
  - '_PR_NUMBER=$_PR_NUMBER'
  - '_MODEL_ROOT=$_MODEL_ROOT'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - '_REPO_SLUG=$_REPO_SLUG'
  - 'BRANCH_NAME=$BRANCH_NAME'
  waitFor: ['validator prep']
  id: 'misc-checks'

############### OC-PYANG ###############
- name: 'us-west1-docker.pkg.dev/$PROJECT_ID/models-ci/models-ci-image'
  entrypoint: 'bash'
  args: ['-c', '/go/src/github.com/openconfig/models-ci/validators/oc-pyang/test.sh']
  secretEnv: ['GITHUB_ACCESS_TOKEN']
  env:
  - 'GOPATH=/go'
  - '_PR_NUMBER=$_PR_NUMBER'
  - '_MODEL_ROOT=$_MODEL_ROOT'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - '_REPO_SLUG=$_REPO_SLUG'
  - 'BRANCH_NAME=$BRANCH_NAME'
  - '_OC_PYANG_VERSION=$_OC_PYANG_VERSION'
  volumes:
  - name: 'gopath'
    path: /go
  waitFor: ['validator prep']
  id: 'oc-pyang'

############### GOYANG/YGOT ###############
- name: 'golang'
  entrypoint: 'go'
  args: ['install', 'github.com/openconfig/ygot/generator@latest']
  volumes:
  - name: 'gopath'
    path: /go
  env:
  - 'GOPATH=/go'
  waitFor: ['go path creation']
  id: 'goyang-ygot prep'
- name: 'us-west1-docker.pkg.dev/$PROJECT_ID/models-ci/models-ci-image'
  entrypoint: 'bash'
  args: ['-c', "/go/src/github.com/openconfig/models-ci/validators/goyang-ygot/test.sh"]
  secretEnv: ['GITHUB_ACCESS_TOKEN']
  volumes:
  - name: 'gopath'
    path: /go
  env:
  - 'GOPATH=/go'
  - '_PR_NUMBER=$_PR_NUMBER'
  - '_MODEL_ROOT=$_MODEL_ROOT'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - '_REPO_SLUG=$_REPO_SLUG'
  - 'BRANCH_NAME=$BRANCH_NAME'
  waitFor: ['validator prep', 'goyang-ygot prep', 'oc-pyang']
  id: 'goyang-ygot'

############### PYANG ###############
- name: 'us-west1-docker.pkg.dev/$PROJECT_ID/models-ci/models-ci-image'
  entrypoint: 'bash'
  args: ['-c', '/go/src/github.com/openconfig/models-ci/validators/pyang/test.sh']
  secretEnv: ['GITHUB_ACCESS_TOKEN']
  env:
  - 'GOPATH=/go'
  - '_PR_NUMBER=$_PR_NUMBER'
  - '_MODEL_ROOT=$_MODEL_ROOT'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - '_REPO_SLUG=$_REPO_SLUG'
  - 'BRANCH_NAME=$BRANCH_NAME'
  volumes:
  - name: 'gopath'
    path: /go
  waitFor: ['validator prep', 'oc-pyang']
  id: 'pyang'

############### PYANGBIND ###############
- name: 'us-west1-docker.pkg.dev/$PROJECT_ID/models-ci/models-ci-image'
  entrypoint: 'bash'
  args: ['-c', '/go/src/github.com/openconfig/models-ci/validators/pyangbind/test.sh']
  secretEnv: ['GITHUB_ACCESS_TOKEN']
  env:
  - 'GOPATH=/go'
  - '_PR_NUMBER=$_PR_NUMBER'
  - '_MODEL_ROOT=$_MODEL_ROOT'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - '_REPO_SLUG=$_REPO_SLUG'
  - 'BRANCH_NAME=$BRANCH_NAME'
  volumes:
  - name: 'gopath'
    path: /go
  waitFor: ['validator prep', 'oc-pyang']
  id: 'pyangbind'

############### COMPATIBILITY REPORT ###############
- name: 'us-west1-docker.pkg.dev/$PROJECT_ID/models-ci/models-ci-image'
  entrypoint: 'bash'
  args: ['-c', '/go/src/github.com/openconfig/models-ci/validators/compat_report.sh']
  secretEnv: ['GITHUB_ACCESS_TOKEN']
  env:
  - 'GOPATH=/go'
  - '_PR_NUMBER=$_PR_NUMBER'
  - '_MODEL_ROOT=$_MODEL_ROOT'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - '_REPO_SLUG=$_REPO_SLUG'
  - 'BRANCH_NAME=$BRANCH_NAME'
  volumes:
  - name: 'gopath'
    path: /go
  id: 'compat-report'

timeout: 600s
options:
  machineType: 'E2_HIGHCPU_32'

availableSecrets:
  inline:
  - kmsKeyName: 'projects/$PROJECT_ID/locations/global/keyRings/keyring0/cryptoKeys/key0'
    envMap:
      # This is the encrypted version of the token.
      GITHUB_ACCESS_TOKEN: 'CiQAvY6emxdh1dn1h9yW/IXSsGQE8l2L39zL8zT8lugxP4zsxBcSUQACTwBYgV0FHz18eP4bqQP6v9Co5ScbuOY24VgquPjtjGumwmdo68/Mn6P6uNn2DOUULvnHfOdpSG865RPGlVSM7kCo5n5tR2e9oskvYfMFWA=='
