- name: openconfig-bgp
  docs:
    - yang/bgp/openconfig-bgp-types.yang
    - yang/bgp/openconfig-bgp.yang
    - yang/bgp/openconfig-bgp-bmp.yang
  build:
    - yang/bgp/openconfig-bgp.yang
    - yang/bgp/openconfig-bgp-bmp.yang
  run-ci: true
