- name: openconfig-bgp
  docs:
    - yang/bgp/openconfig-bgp-types.yang
    - yang/bgp/openconfig-bgp.yang
    - yang/bgp/openconfig-bgp-ext.yang
    - yang/bgp/openconfig-bgp-policy-ext.yang
    - yang/bgp/openconfig-bgp-evpn-ext.yang
  build:
    - yang/bgp/openconfig-bgp.yang
    - yang/bgp/openconfig-bgp-ext.yang
    - yang/bgp/openconfig-bgp-policy-ext.yang
    - yang/bgp/openconfig-bgp-evpn-ext.yang
  run-ci: true
