- name: openconfig-aft
  docs:
    - yang/aft/openconfig-aft.yang
    - yang/aft/openconfig-aft-types.yang
  build:
    - yang/network-instance/openconfig-network-instance.yang
    - yang/aft/openconfig-aft-network-instance.yang
  run-ci: true
