- name: openconfig-security
  docs:
    - yang/security/openconfig-security.yang
    - yang/security/openconfig-security-ike.yang
    - yang/security/openconfig-security-ipsec.yang
    - yang/security/openconfig-security-types.yang
  build:
    - yang/security/openconfig-security.yang
    - yang/security/openconfig-security-ike.yang
    - yang/security/openconfig-security-ipsec.yang
    - yang/security/openconfig-security-types.yang
  run-ci: true
