- name: openconfig-oam
  docs:
    - yang/oam/openconfig-oam.yang
    - yang/oam/openconfig-cfm-types.yang
    - yang/oam/openconfig-oam-cfm.yang
  build:
    - yang/oam/openconfig-oam.yang
    - yang/oam/openconfig-oam-cfm.yang
  run-ci: true
