- name: openconfig-multicast
  docs:
    - yang/multicast/openconfig-igmp-types.yang
    - yang/multicast/openconfig-igmp.yang
    - yang/multicast/openconfig-pim-types.yang
    - yang/multicast/openconfig-pim.yang
    - yang/multicast/openconfig-msdp.yang
    - yang/multicast/openconfig-mld.yang
  build:
    - yang/multicast/openconfig-igmp.yang
    - yang/multicast/openconfig-pim.yang
    - yang/multicast/openconfig-msdp.yang
    - yang/multicast/openconfig-mld.yang
  run-ci: true
