- name: openconfig-sampling
  docs:
    - yang/sampling/openconfig-sampling.yang
    - yang/sampling/openconfig-sampling-sflow.yang
    - yang/sampling/openconfig-sampling-gnpsi.yang
  build:
    - yang/sampling/openconfig-sampling.yang
    - yang/sampling/openconfig-sampling-sflow.yang
    - yang/sampling/openconfig-sampling-gnpsi.yang
  run-ci: true
