- name: openconfig-kubernetes
  docs:
    - yang/kubernetes/openconfig-kubernetes-types.yang
    - yang/kubernetes/openconfig-kubernetes.yang
  build:
    - yang/kubernetes/openconfig-kubernetes.yang
  run-ci: true
