- name: openconfig-firewall
  docs:
    - yang/firewall/openconfig-fw-high-availability.yang
    - yang/firewall/openconfig-fw-link-monitoring.yang
  build:
    - yang/firewall/openconfig-fw-high-availability.yang
  run-ci: true
