- name: openconfig-ate
  docs:
    - yang/ate/openconfig-ate-flow.yang
    - yang/ate/openconfig-ate-intf.yang
  build:
    - yang/ate/openconfig-ate-flow.yang
    - yang/ate/openconfig-ate-intf.yang
  run-ci: true
