- name: openconfig-ptp
  docs:
    - yang/ptp/openconfig-ptp-types.yang
    - yang/ptp/openconfig-ptp.yang
  build:
    - yang/ptp/openconfig-ptp-types.yang
    - yang/ptp/openconfig-ptp.yang
  run-ci: true