- name: openconfig-ospf
  docs:
    - yang/ospf/openconfig-ospf-types.yang
    - yang/ospf/openconfig-ospfv2.yang
    - yang/ospf/openconfig-ospf.yang
    - yang/ospf/openconfig-ospfv3-area-interface.yang
  build:
    - yang/network-instance/openconfig-network-instance.yang
    - yang/policy/openconfig-routing-policy.yang
    - yang/ospf/openconfig-ospf-policy.yang
    - yang/ospf/openconfig-ospfv3-area-interface.yang
  run-ci: true
