- name: openconfig-synce
  docs:
    - yang/synce/openconfig-synce-types.yang
    - yang/synce/openconfig-synce.yang
  build:
    - yang/synce/openconfig-synce-types.yang
    - yang/synce/openconfig-synce.yang
  run-ci: true
