- name: openconfig-catalog
  build:
    - yang/catalog/openconfig-module-catalog.yang
  docs:
    - yang/catalog/openconfig-catalog-types.yang
    - yang/catalog/openconfig-module-catalog.yang
  run-ci: false
