- name: openconfig-interfaces
  docs:
    - yang/interfaces/openconfig-if-types.yang
    - yang/interfaces/openconfig-interfaces.yang
    - yang/interfaces/openconfig-if-ip.yang
    - yang/interfaces/openconfig-if-aggregate.yang
    - yang/interfaces/openconfig-if-ethernet.yang
    - yang/interfaces/openconfig-if-ethernet-ext.yang
    - yang/interfaces/openconfig-if-poe.yang
    - yang/interfaces/openconfig-if-ip-ext.yang
    - yang/interfaces/openconfig-if-8021x.yang
    - yang/vlan/openconfig-vlan.yang
    - yang/interfaces/openconfig-if-tunnel.yang
    - yang/platform/openconfig-platform-port.yang
    - yang/platform/openconfig-platform-transceiver.yang
    - yang/interfaces/openconfig-if-sdn-ext.yang
  build:
    - yang/interfaces/openconfig-interfaces.yang
    - yang/interfaces/openconfig-if-ip.yang
    - yang/interfaces/openconfig-if-aggregate.yang
    - yang/interfaces/openconfig-if-ethernet.yang
    - yang/interfaces/openconfig-if-ethernet-ext.yang
    - yang/interfaces/openconfig-if-poe.yang
    - yang/interfaces/openconfig-if-ip-ext.yang
    - yang/interfaces/openconfig-if-8021x.yang
    - yang/vlan/openconfig-vlan.yang
    - yang/interfaces/openconfig-if-tunnel.yang
    - yang/platform/openconfig-platform-port.yang
    - yang/platform/openconfig-platform-transceiver.yang
    - yang/interfaces/openconfig-if-sdn-ext.yang
  run-ci: true
