- name: openconfig-interfaces
  docs:
    - yang/interfaces/openconfig-interfaces.yang
    - yang/interfaces/openconfig-if-ip.yang
    - yang/interfaces/openconfig-if-aggregate.yang
    - yang/interfaces/openconfig-if-ethernet.yang
    - yang/interfaces/openconfig-if-poe.yang
    - yang/interfaces/openconfig-if-ip-ext.yang
    - yang/vlan/openconfig-vlan.yang
  build:
    - yang/interfaces/openconfig-interfaces.yang
    - yang/interfaces/openconfig-if-ip.yang
    - yang/interfaces/openconfig-if-aggregate.yang
    - yang/interfaces/openconfig-if-ethernet.yang
    - yang/interfaces/openconfig-if-poe.yang
    - yang/interfaces/openconfig-if-ip-ext.yang
    - yang/vlan/openconfig-vlan.yang
  run-ci: true
