- name: openconfig-mpls
  docs:
    - yang/mpls/openconfig-mpls-types.yang
    - yang/mpls/openconfig-mpls.yang
    - yang/mpls/openconfig-mpls-network-instance.yang
  build:
    - yang/mpls/openconfig-mpls.yang
    - yang/mpls/openconfig-mpls-network-instance.yang
  run-ci: true
