name: Trailing whitespace

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Trailing whitespace
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: bash scripts/find_trailing_whitespace.sh
