- name: openconfig-local-routing
  docs:
    - yang/local-routing/openconfig-local-routing.yang
  build:
    - yang/local-routing/openconfig-local-routing.yang
  run-ci: true
- name: openconfig-local-routing-network-instance
  docs:
    - yang/network-instance/openconfig-network-instance.yang
    - yang/local-routing/openconfig-local-routing-network-instance.yang
